config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'session#new'
  post 'sign_in', to: 'session#create'

  get 'password', to: 'password#edit'
  patch 'password', to: 'password#update'

  get 'password/reset', to: 'password_reset#new'
  post 'password/reset', to: 'password_reset#create'

  get 'password/reset/edit', to: 'password_reset#edit'
  patch 'password/reset/edit', to: 'password_reset#update'

  get '/auth/twitter/callback' , to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts

  resources :tweets

  resources :king, only: [:edit, :new]



  delete 'logout', to: 'session#destroy'
  root to: 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum: 1 , maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 1.hour.from_now
  end
  def published?
    tweet_id?
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  validates :username, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :twitter_accounts
  has_many :tweets
  validates :email , presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'email must be valid' }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
  def require_user_logged_in!
    redirect_to sign_in_path, alert: 'You must be signIn to edit password' if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])

    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter

    twitter_account = Current.user.twitter_accounts.where(username: auth.info.username).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      username: auth.info.nickname,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret,
    )
    redirect_to twitter_accounts_path, notice: 'twitter account connected'
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!
  def new

  end
  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'password updated'
    else
      flash[:alert] = 'password do not match'
      render :new
    end
  end

  def edit

  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: 'If an account with that email is present you should receive an email in 5 minutes'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: 'your token has expired'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to sign_in_path, notice: 'Your password has been reset'
    else
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_param)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'successfully created'
    else
      render :new
    end
  end


  private
  def user_param
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'logged in successfully'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'you are now logged out'
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:edit, :show, :update, :destroy]
  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice:  'Your tweet has been scheduled'

    else
      render :new
    end
  end
  def edit
    render plain: 'hello'
  end
  def show

  end
  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet was updated successfully"
    else
      render :edit
    end
  end
  def destroy

  end
  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body , :publish_at)
  end
  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController  < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end
  def destroy
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
    @twitter_account.destroy
    redirect_to twitter_accounts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h2>About </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoTweet</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'shared/nav_bar' %>
<div class="container">
    <%= render partial: 'shared/flash' %>
  <%= yield %>
</div>

</body>
</html>

app/views/main/index.html.erb
<div class="container d-flex justify-content-center align-items-center flex-column">
  <h1 > Welcome to Schedule tweet  </h1>
  <% if Current.user %>
  Logged in as : <%= Current.user.email %>
    <%= button_to 'Logout', logout_path, method: :delete, class: 'btn btn-warning'  %>
  <%end %>
</div>

app/views/password/new.html.erb
<h1>Edit Password</h1>

<%= form_with model: Current.user, url: password_path do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-warning">
      <% form.object.errors.full_messages.each do |msg| %>
        <div><%= msg.to_s %></div>

      <% end %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :password_field %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit 'Update Password', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/password_reset/edit.html.erb
<h1>Reset Password</h1>

<%= form_with model: @user,  url: password_reset_edit_path(token: params[:token]) do |form| %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :password_field %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit 'Update Password', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/password_reset/new.html.erb
<h2> Forgot password</h2>


<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit 'Confirm email', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/session/new.html.erb
<h2>Sign in</h2>

<%= form_with url: sign_in_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit 'SignIn', class: 'btn btn-primary' %>
  </div>
<%end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice]  %>
  </div>
<%end %>

<% if flash[:alert] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:alert]  %>
  </div>
<%end %>

app/views/shared/_form_error.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |msg| %>
      <div><%= msg.to_s %></div>

    <% end %>
  </div>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Muuve', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Tweets', tweets_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-3 d-flex align-items-center">
        <% if Current.user %>

          <%= link_to Current.user.email.split('@')[0].capitalize,  root_path , class: 'text-decoration-none text-black-50' %>
            <%= link_to 'twitter', twitter_accounts_path , class: 'btn btn-primary mx-2 text-black-50'%>
          <%= button_to 'Logout', logout_path, method: :delete, class: 'btn btn-warning mx-2 text-black-50' %>
        <% else %>
          <%= link_to 'Log In', sign_in_path, class: 'btn btn-primary mx-2 text-black-50' %>
          <%= link_to 'Sign Up', sign_up_path, class: 'btn btn-warning mx-2 text-black-50' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
  <%= render "shared/form_error", form: form %>

  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control" } %>
    <%= link_to "Connect your Twitter Account", "/auth/twitter" %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="form-control">
      <%= form.datetime_select :publish_at %>
    </div>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary" %>

  <% if form.object.persisted? %>
    <%= link_to "Delete", form.object, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card my-2">
  <div class="card-header">
    Tweet <%= tweet.id %>
  </div>
  <div class="card-body d-flex justify-content-between">
    <blockquote class="blockquote mb-0">
      <p><%= tweet.body %></p>
      <footer class="blockquote-footer px-1 gap-1"><%= tweet.twitter_account[:name] %>


        <% if tweet.published? %>

          <%= link_to 'view tweet', "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}" %>
        <% else %>
          <cite class="px-2" title="scheduled time ">Scheduled
            time:  <%= tweet.publish_at.to_formatted_s(:short) %></cite>
          <cite class="px-2"> edit tweet
          </cite> </footer>
<%= link_to 'edit', new_tweet_path(tweet) %>
        <% end %>
        </blockquote>
    <p> <%= tweet.tweet_id %></p>

    <button type="button" class="btn-close" aria-label="Close">
      <% link_to @tweet %> </button>


  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex flex-column align-items-center">
  <h1>Tweets</h1>
  <% if Current.user.twitter_accounts.any? %>
  <%= link_to 'Schedule a tweet', new_tweet_path, class: 'btn btn-secondary' %>
  <% end %>
  <% if Current.user.twitter_accounts.none? %>
  <%= button_to 'connect your twitter account', '/auth/twitter', class: 'btn btn-secondary' %>
  <% end %>
</div>

  <%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= render 'tweets/form', tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="container">

  <div class="sub-nav d-flex m-2 justify-content-between align-items-center">
    <h1> Twitter Accounts</h1>
    <%= button_to 'connect a twitter account', '/auth/twitter', method: :post, class: 'btn btn-secondary' %>
  </div>

  <div class="container ">
    <% @twitter_accounts.each do |account| %>
      <div class="outer d-flex justify-content-between p-1 align-items-center">
        <div class="profile d-flex mx-1">
          <%= image_tag account[:image] %>
        <div class="left d-flex flex-column mx-1">
          <div class="name">
            <%= account[:name] %>
          </div>
          <div class="username">
            <%= account[:username] %>
          </div>
        </div>
        </div>
        <%= button_to 'remove', account, method: :delete, class: 'btn btn-danger p-2' %>
      </div>
    <% end %>
  </div>

</div>